/****** FILE: reece/javascript/reece.js *****/
;(function($){window.Reece=(function(){var log=function(msg){if(typeof console!='undefined'&&console.log){console.log(msg);}else{}};var sprintf=function(){var regex=/%%|%(\d+\$)?([-+\'#0 ]*)(\*\d+\$|\*|\d+)?(\.(\*\d+\$|\*|\d+))?([scboxXuideEfFgG])/g;var a=arguments;var i=0;var format=a[i++];var pad=function(str,len,chr,leftJustify){if(!chr){chr=' ';}
var padding=(str.length>=len)?'':new Array(1+len-str.length>>>0).join(chr);return leftJustify?str+padding:padding+str;};var justify=function(value,prefix,leftJustify,minWidth,zeroPad,customPadChar){var diff=minWidth-value.length;if(diff>0){if(leftJustify||!zeroPad){value=pad(value,minWidth,customPadChar,leftJustify);}else{value=value.slice(0,prefix.length)+pad('',diff,'0',true)+value.slice(prefix.length);}}
return value;};var formatBaseX=function(value,base,prefix,leftJustify,minWidth,precision,zeroPad){var number=value>>>0;prefix=prefix&&number&&{'2':'0b','8':'0','16':'0x'}[base]||'';value=prefix+pad(number.toString(base),precision||0,'0',false);return justify(value,prefix,leftJustify,minWidth,zeroPad);};var formatString=function(value,leftJustify,minWidth,precision,zeroPad,customPadChar){if(precision!=null){value=value.slice(0,precision);}
return justify(value,'',leftJustify,minWidth,zeroPad,customPadChar);};var doFormat=function(substring,valueIndex,flags,minWidth,_,precision,type){var number,prefix,method,textTransform,value;if(substring==='%%'){return'%';}
var leftJustify=false;var positivePrefix='';var zeroPad=false;var prefixBaseX=false;var customPadChar=' ';var flagsl=flags.length;for(var j=0;flags&&j<flagsl;j++){switch(flags.charAt(j)){case' ':positivePrefix=' ';break;case'+':positivePrefix='+';break;case'-':leftJustify=true;break;case"'":customPadChar=flags.charAt(j+1);break;case'0':zeroPad=true;customPadChar='0';break;case'#':prefixBaseX=true;break;}}
if(!minWidth){minWidth=0;}else if(minWidth==='*'){minWidth=+a[i++];}else if(minWidth.charAt(0)=='*'){minWidth=+a[minWidth.slice(1,-1)];}else{minWidth=+minWidth;}
if(minWidth<0){minWidth=-minWidth;leftJustify=true;}
if(!isFinite(minWidth)){throw new Error('sprintf: (minimum-)width must be finite');}
if(!precision){precision='fFeE'.indexOf(type)>-1?6:(type==='d')?0:undefined;}else if(precision==='*'){precision=+a[i++];}else if(precision.charAt(0)=='*'){precision=+a[precision.slice(1,-1)];}else{precision=+precision;}
value=valueIndex?a[valueIndex.slice(0,-1)]:a[i++];switch(type){case's':return formatString(String(value),leftJustify,minWidth,precision,zeroPad,customPadChar);case'c':return formatString(String.fromCharCode(+value),leftJustify,minWidth,precision,zeroPad);case'b':return formatBaseX(value,2,prefixBaseX,leftJustify,minWidth,precision,zeroPad);case'o':return formatBaseX(value,8,prefixBaseX,leftJustify,minWidth,precision,zeroPad);case'x':return formatBaseX(value,16,prefixBaseX,leftJustify,minWidth,precision,zeroPad);case'X':return formatBaseX(value,16,prefixBaseX,leftJustify,minWidth,precision,zeroPad).toUpperCase();case'u':return formatBaseX(value,10,prefixBaseX,leftJustify,minWidth,precision,zeroPad);case'i':case'd':number=+value||0;number=Math.round(number-number%1);prefix=number<0?'-':positivePrefix;value=prefix+pad(String(Math.abs(number)),precision,'0',false);return justify(value,prefix,leftJustify,minWidth,zeroPad);case'e':case'E':case'f':case'F':case'g':case'G':number=+value;prefix=number<0?'-':positivePrefix;method=['toExponential','toFixed','toPrecision']['efg'.indexOf(type.toLowerCase())];textTransform=['toString','toUpperCase']['eEfFgG'.indexOf(type)%2];value=prefix+Math.abs(number)[method](precision);return justify(value,prefix,leftJustify,minWidth,zeroPad)[textTransform]();default:return substring;}};return format.replace(regex,doFormat);};var scrollToElementBySelector=function(a){$("html, body").animate({scrollTop:($(a).offset().top-60)},800);}
var workaroundIosFixedPositionBug=function(){var isIosSafari=/(iPad|iPhone|iPod)/g.test(navigator.userAgent);if(isIosSafari){$('.ocmain-wrapper').on("focus","input, textarea",function(){$('body').addClass('keyboard-shown');});$('.ocmain-wrapper').on("blur","input, textarea",function(){$('body').removeClass('keyboard-shown');_.defer(function(){window.scrollTo(0,$('body')[0].scrollHeight);});});}}
var getCookie=function(cookiename){var name=cookiename+'=';var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var trimmed=cookies[i].trim();if(trimmed.indexOf(name)==0){return trimmed.substring(name.length,trimmed.length);}}}
return{log:log,sprintf:sprintf,scrollToElementBySelector:scrollToElementBySelector,getCookie:getCookie};})();$(function(){$(".pinterest").on("click",function(e){e.preventDefault();pinClick();});$('iframe').each(function(){var url=$(this).attr("src");var id=$(this).attr('id');if(!url){return;}
if(id&&(id=="__gwt_historyFrame")){return;}
var spacer="?";if(url.indexOf("?")!=-1){var spacer="&";}
$(this).attr("src",url+spacer+"wmode=transparent");});$('.site-message-close').on("click",function(){var id=$(this).attr('data-id');var times=$(this).attr('data-times');$('.site-message, .site-message-icon').remove();updateMessageCookie(id,times);});});function updateMessageCookie(id,times){var messageCookie=Reece.getCookie('reece-message');var exists=false;if(messageCookie){var args=messageCookie.split('#');var storedId=args[0];var timesAlreadyClosed=parseInt(args[1]);if(storedId==id){exists=true;timesAlreadyClosed++;document.cookie='reece-message='+id+'#'+timesAlreadyClosed+'; expires=Fri, 1 Jan 2021 00:00:01 UTC; path=/';}}
if(!exists){document.cookie='reece-message='+id+'#1; expires=Fri, 1 Jan 2021 00:00:01 UTC; path=/';}}
function pinClick(){PinterestSpecial.popupPinItForm();return false;}
$(function(){if($(".carousel-control").length>0){BackgroundCheck.init({targets:'.carousel-control',images:'.carousel .item img'});$(document).ready(function(){BackgroundCheck.refresh();});$('.carousel').bind('slid',function(){BackgroundCheck.refresh();});}
if($('.accountList').length>0){$('.accountList .selectAccount').on("click",function(e){e.preventDefault();if($(this).hasClass('current')){return;}
$('.accountDropDown .dropdown-toggle').html("<span class='ladda-spinner'></span>");var accountNumber=$(this).data('accountnumber');var setAccountCookieURL='';var redirectURL='';if(window.location.port!=='80'&&window.location.port!==""){setAccountCookieURL=window.location.protocol+"//"+window.location.hostname+":"+window.location.port+'/jsonservice/ReeceCookie/setAccountNumber/accountNumber/'+accountNumber;if(window.location.port==='8080'){redirectURL="https://"+window.location.hostname+":8443/myaccount/home";}
else{redirectURL="https://"+window.location.hostname+":"+window.location.port+"/myaccount/home";}}
else{setAccountCookieURL=window.location.protocol+"//"+window.location.hostname+'/jsonservice/ReeceCookie/setAccountNumber/accountNumber/'+accountNumber;redirectURL="https://"+window.location.hostname+"/myaccount/home";}
$.ajax(setAccountCookieURL,{dataType:'json',success:function(data){window.location.href=redirectURL;}});});}});if(typeof bowser!='undefined'){if(bowser.c){if(!$('body').hasClass('myaccount-legacy-theme')){$('.browser-message .alert').show();}}}})(jQuery);;

/****** FILE: reece/javascript/tracking.js *****/
;(function($){Reece.Tracking=(function(){var track=function(category,action,label){if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent',category,action,label]);}else if(typeof ga!=='undefined'){ga('send','event',category,action,label);}};return{track:track};})();})(jQuery);;

/****** FILE: themes/reece/javascript/reece-ocnav.js *****/

$(document).ready(function(){var body=$('body');$('.ocmain-wrapper').unbind('swiperight').bind('swiperight',function(){body.removeClass('off-canvas-open');});$(".topNav .btn-navbar").unbind('click').bind('click',function(){if(body.hasClass('off-canvas-open')){body.removeClass('off-canvas-open');}
else{body.addClass('off-canvas-open');}});});;

/****** FILE: themes/reece/javascript/reece-site.js *****/
;(function($){$(document).ready(function(){if($.fn.fitVids){$(".ocmain-wrapper, .cboxContent").fitVids();}
if($(".fancybox").length>0){$('.fancybox').fancybox({'type':'iframe','title':false,maxWidth:800,maxHeight:450,minHeight:180,fitToView:false,width:'85%',height:'65%',autoSize:false,closeClick:false});}});})(jQuery);;

/****** FILE: themes/reece/javascript/matchMedia.js *****/

window.matchMedia=window.matchMedia||(function(doc,undefined){"use strict";var bool,docElem=doc.documentElement,refNode=docElem.firstElementChild||docElem.firstChild,fakeBody=doc.createElement("body"),div=doc.createElement("div");div.id="mq-test-1";div.style.cssText="position:absolute;top:-100em";fakeBody.style.background="none";fakeBody.appendChild(div);return function(q){div.innerHTML="&shy;<style media=\""+q+"\"> #mq-test-1 { width: 42px; }</style>";docElem.insertBefore(fakeBody,refNode);bool=div.offsetWidth===42;docElem.removeChild(fakeBody);return{matches:bool,media:q};};}(document));;

/****** FILE: themes/reece/javascript/modal-window-fix.js *****/
;(function($){$(document).ready(function(){var $modals=$(".modal,#sysReqModal,#disclaimer");$modals.remove();$("body").append($modals);$(".showWindow").on("click",function(e){if(matchMedia('(min-width: 480px)').matches){e.preventDefault();$("#myModal .modal-body").html("<img src='"+$(this).data('large')+"'>");$("#myModal").modal();}
else{e.preventDefault();}});});})(jQuery);;

/****** FILE: themes/reece/javascript/reece-carousel.js *****/

$(document).ready(function(){var $carousel=$('[data-bs-carousel]');if($carousel.length!=0){$carousel.swiperight(function(){$carousel.carousel('prev');});$carousel.swipeleft(function(){$carousel.carousel('next');});$.each($carousel,function(index){var interval=$(this).data('bs-carousel-interval'),undefined;var pause=$(this).data('bs-carousel-pause'),undefined;if(interval===undefined){$(this).carousel();}
else{$(this).carousel({interval:parseInt(interval)});}
if(pause!==undefined){$(this).mouseover(function(){$(this).carousel('pause');});$(this).mouseout(function(){$(this).carousel('cycle');});}});}
$(document).on('click.carousel-slide.data-api','[data-carousel-slide]',function(e){e.preventDefault();var $clicked=$(e.currentTarget),href,$target=$($clicked.attr('data-target')||(href=$clicked.attr('href'))&&href.replace(/.*(?=#[^\s]+$)/,'')),id_selector=$clicked.data("carouselSlide");id=parseInt(id_selector);$target.carousel(id);});});;

/****** FILE: themes/reece/javascript/reece-home.js *****/
;(function($){$(document).ready(function(){$(".searchstores").on('click',function(e){e.preventDefault();var $storefinderform=$(this).parents('form');var valid=validateHomePageStoreFinderForm($storefinderform);if(valid){var params={"address":$("input[name='address']",$storefinderform).val(),"businessUnitIdentifiers":getSelectedStoreTypes($storefinderform)}
if($storefinderform.is("#mobileStorefinderSearch")){params['limit']=4;}
updateBrowserUrl($.param(params,true));}});$(".use-location").on('click',function(){searchViaUserLocation();});});function validateHomePageStoreFinderForm(form){if($("input[name='address']",form).val()==""||($("input[name='address']",form).val().length<3)){if(form.attr('id')=='mobileStorefinderSearch'){alert("Please enter a valid postcode.");}
else{alert("Please enter a valid suburb and state or postcode.");}
return;}
return true;}
function getSelectedStoreTypes(form){var types=new Array();var allTypes=new Array();if($("select[name='homepageStoreType']",form).length>0){$("select[name='homepageStoreType'] > option",form).each(function(){if($(this).prop('selected')&&$(this).val()!==''){types.push($(this).val());}
if($(this).val()!==''){allTypes.push($(this).val());}});if(types.length==0){types=allTypes;}}
else if($("input[name='businessUnitIdentifiers'][type='checkbox']",form).length>0){$("input[name='businessUnitIdentifiers'][type='checkbox']",form).each(function(){if($(this).prop('checked')){types.push($(this).val());}
allTypes.push($(this).val());});if(types.length==0){types=allTypes;}}
else{types.push($("input[name='businessUnitIdentifiers']",form).val());}
return types;}
function updateBrowserUrl(params){params=$.base64Encode(params);if(window.location.port!==80&&window.location.port!==""){window.location=window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/storefinder#"+params;}
else{window.location=window.location.protocol+"//"+window.location.hostname+"/storefinder#"+params;}}
function searchViaUserLocation(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(geoSuccess,geoError);}else{alert('geolocation not supported');}}
function geoSuccess(position){var form=$('form.storefinderform');if($("#mobileStorefinderSearch").length>0){form=$("#mobileStorefinderSearch");}
var params={"lat":position.coords.latitude,"lng":position.coords.longitude,"limit":4,"businessUnitIdentifiers":getSelectedStoreTypes(form)};updateBrowserUrl($.param(params,true));}
function geoError(err){var error=err.code;var msg;switch(error){case 0:var strErrorCode=error.code.toString();msg="Unknown Error: "+strErrorCode;break;case 1:msg="User Permission Denied";break;case 2:msg="Position Unavailable";break;case 3:msg="Timeout";break;}
alert(msg);}
if($('form.storefinderform input[name="address"]').length>0){$('form.storefinderform input[name="address"]').typeahead({source:function(query,process){return $.get('/cc/myaccount/api/StoreFinder/postcode',{query:query},function(data){var newData=[];$.each(data,function(){newData.push(this.suburb+' '+this.codeNumber+', '+this.state);});return process(newData);});},minLength:3});}
$('input[name="address"]').on('input',function(e){var form=$(this).parents('form:first');var length=4;if(form.hasClass('storefinderform')){length=3;}
if($(this).val().length>=length){form.find(".searchstores").prop('disabled',false);}
else{form.find(".searchstores").prop('disabled',true);}});})(jQuery);;

/****** FILE: themes/reece/javascript/reece-products.js *****/
;(function($){var navBreadCrumbItemsInitialTotalWidth=0,navBreadCrumbItemsMinimumWidth=0,previousULWidth=0;$(document).ready(function(){$(".toggleGroup").on('click',function(){$ul=$('ul[data-list="'+$(this).data('toggle')+'"]');$("li",$ul).toggle();});$("input[name=userpostcode]").keypress(function(e){if(e.keyCode==13){doPostCodeSearch($(this));}});$(".postcodeSearch").on('click',function(){doPostCodeSearch($(this));});$(".changeLocation").on('click',function(){$(".location").hide();$(".setlocation").show();});$("#product-filters .well").each(function(i){if($(this).outerHeight()>365){hidenthElementsOnwards($(this),"ul li",250);$(this).append("<br><a class='more-brands-button toggleWell'><span>Show more brands</span></a>");}});$("#product-filters .toggleWell").on("click",function(e){e.preventDefault();var linkHtml="Show more Brands";var action="hide";var $parentWell=$(this).parents(".well");if($("li:hidden",$parentWell).html()){linkHtml="Less Brands";action="show";$(this).removeClass('more-brands-button').addClass('less-brands-button');}else{$(this).removeClass('less-brands-button').addClass('more-brands-button');}
if(action=="show"){$("ul li",$parentWell).show();}else{hidenthElementsOnwards($parentWell,"ul li",250);}
$(this).html(linkHtml);});var listCookie=getCookie("reece-product-compare");if(listCookie){if($('.addtolist').length>0){var productCode=$('.addtolist').data('productcode');var listArray=listCookie.split(",");var productInList=isProductInList(productCode,listArray);if(productInList){$('.addtolist').html("REMOVE").addClass("btn-cart removeFromList").removeClass("addtolist");}
$('.listCount').html(listArray.length);}}
$('.addtolist').live('click',function(){var productCode=$(this).data('productcode');var array=new Array();var compareCookie=getCookie("reece-product-compare");if(compareCookie){array=compareCookie.split(",");var productInList=isProductInList(productCode,array);if(productInList){return false;}}
array.push(productCode);$('.addtolist').html("REMOVE").addClass("btn-cart removeFromList").removeClass("addtolist");$('.listCount').show().html(array.length);document.cookie='reece-product-compare='+array.toString()+'; expires=Fri, 1 Jan 2021 00:00:01 UTC; path=/';});$('.addtocart').live('click',function(){addToCart();});$('input[name="cartQty"]').on('input',function(e){this.value=this.value.replace(/[^0-9]/g,'');this.value=this.value.replace(/^0/,'');if(this.value==0||this.value>999){$('.btn-cart').removeClass('addtocart').addClass('disabled');$('.qty-tip').html('Qty limit from 1-999').show();}else{$('.btn-cart').removeClass('disabled').addClass('addtocart');$('.qty-tip').hide();}});$('input[name="cartQty"]').on('keyup',function(e){if(e.keyCode==13&&$('.btn-cart').hasClass('addtocart')){addToCart();}});if($(".myProductList").length>0){if(!listCookie){$(".myProductList").hide();$(".noproducts").removeClass("hidden");}}
$('.removeFromList').live('click',function(){var productCode=$(this).data('productcode');var compareCookie=getCookie("reece-product-compare");if(compareCookie){var list=compareCookie.split(",");var newList=removeProductFromList(productCode,list);var newCookie;if(newList.length>0){newCookie='reece-product-compare='+newList.toString()+'; expires=Fri, 1 Jan 2021 00:00:01 UTC; path=/';}else{newCookie='reece-product-compare=; expires=Thu, 1 Jan 1970 00:00:01 UTC; path=/';}
if($(".myProductList").length>0){$(".row-"+productCode).remove();if($(".comparerow").length==0){$(".myProductListTable").remove();$(".noproducts").removeClass("hidden");$(".printlist").hide();}}else{if(newList.length>0){$('.listCount').html(newList.length);}else{$('.listCount').hide();}
$('.removeFromList').html("ADD TO LIST").removeClass("btn-cart removeFromList").addClass("addtolist");}
document.cookie=newCookie;}else{if($(".myProductList").length>0){$(".myProductList").hide();$(".noproducts").removeClass("hidden");}else{$('.removeFromList').html("Add to My List").removeClass("btn-cart removeFromList").addClass("addtolist");$('.listCount').hide();}}});if($(".printlist").length>0&&$(".myProductList").length==0){$(".printlist").hide();}
$(".back").on('click',function(e){e.preventDefault();window.history.back();});$('.more-products-row .pagList li a').css('display','block').live('click',function(){var clicked=$(this),container=clicked.parents('.products-list:first');if(clicked.hasClass('current')||clicked.hasClass('dots')){return false;}
if(Modernizr.history){$('.products-list .overlay').removeClass('hidden');history.pushState(null,null,clicked.attr('href'));$("<div>").hide().load(clicked.attr('href'),function(){var list=$(this);clicked.addClass('current');container.html(list);list.fadeIn(1000).find('.more-products-row').css('display','block');$('html, body').animate({scrollTop:list.offset().top-40},'slow');});return false;}});if($("ul.breadcrumb").length>0){$('ul.breadcrumb li').each(function(){navBreadCrumbItemsInitialTotalWidth+=$(this).outerWidth();});previousULWidth=$("ul.breadcrumb").outerWidth();resizeBreadCrumbs();$(window).resize(function(){var outerULWidth=$("ul.breadcrumb").outerWidth();if(outerULWidth!=previousULWidth){resizeBreadCrumbs();}});}
sortAttributeColumns();if(shouldLocationModalFire()){initLocationModal();}});function shouldLocationModalFire(){if(typeof localStorage.dismissLocationModal!=='undefined'){return(false);}
var locationCookie=getCookie("reece-user-location");if(locationCookie.length){return(false);}
var profileCookie=getCookie("reece-user-profile");if(profileCookie.length){return(false);}
return(true);}
function initLocationModal(){var locationModal=$('#setlocation-modal');if(locationModal.length){localStorage.dismissLocationModal=1;locationModal.on('shown',function(){$('#setlocation-modal').toggleClass('hidden');var locationModal=$(this);$('#setlocation-modal .dismiss').click(function(e){e.preventDefault();locationModal.modal('hide');return(false);});})
locationModal.modal('show');}}
function doPostCodeSearch(ele){var $parentContainer=ele.closest('.setlocation');var userpostcode=$('input[name=userpostcode]',$parentContainer).val();var currentUrl=window.location.pathname;currentUrl+='/BranchSearch';if(window.location.search&&window.location.search.length){currentUrl=currentUrl+window.location.search;}
if(isNumeric(userpostcode)&&userpostcode.length=="4"){$(".loading",$parentContainer).show();$(".postcodeSearch",$parentContainer).hide();$.ajax({type:"POST",url:currentUrl,data:"postcode="+userpostcode,dataType:'json',success:function(data){if(data){if(data.branches&&data.branches.length>0){setPostCodeResult(userpostcode,data);}else{$(".loading",$parentContainer).hide();$(".postcodeSearch",$parentContainer).show();alert("No Branches found, please try again");}}else{$(".loading",$parentContainer).hide();$(".postcodeSearch",$parentContainer).show();alert("There was an error, Please enter a valid postcode");}},error:function(){$(".loading",$parentContainer).hide();$(".postcodeSearch",$parentContainer).show();alert("There was an error, Please try again later");}});}else{alert("Please enter a valid postcode");}}
function addToCart(){var $button=$('.addtocart');if(!$button){return false;}
$button.removeClass('addtocart').addClass('disabled');$('span',$button).html('PRODUCT ADDED');var prodCode=$('.prod-code').html();var qty=parseInt($('input[name="cartQty"]').val());var desc=$('.brand-desc').html()+' '+$('.prod-desc').html();qty=checkProductCartQuantity(prodCode,qty);if(qty){if(!getProductFromCart(prodCode)){incrementCartTotal();}
updateSummaryTable(prodCode,qty,desc);updateCartCookie(prodCode,qty);}
$('.cart-summary').show();$('input[name="cartQty"]').val(1);setTimeout(function(){$button.removeClass('disabled').addClass('addtocart');$('span',$button).html('ADD TO CART');},700);}
function checkProductCartQuantity(prodCode,qty){var product=getProductFromCart(prodCode);if(product){if(parseInt(product.quantity)>=999){$('.qty-tip').html('999 limit for product in cart').show();qty=0;}else if((parseInt(product.quantity)+parseInt(qty))>999){$('.qty-tip').html('999 limit for product in cart').show();qty=999-parseInt(product.quantity);}}
return qty;}
function getProductFromCart(prodCode){var cartCookie=getCookie("reece-cart");if(cartCookie){cartContents=JSON.parse(cartCookie);var cartLength=cartContents.length;for(var i=0;i<cartLength;i++){if(cartContents[i].productCode===prodCode){return cartContents[i];}}}
return false;}
function updateSummaryTable(prodCode,qty,desc){var $table=$('.cart-summary tbody');if($('tr.row_'+prodCode,$table).length>0){var total=parseInt($('.qty',$('tr.row_'+prodCode)).html());total+=parseInt(qty);$('.qty',$('tr.row_'+prodCode)).html(total)}else{var $row=$('<tr></tr>').addClass('row_'+prodCode);var $desc=$('<td></td>').addClass('desc').html(desc);var $qty=$('<span></span>').addClass('qty').html(qty);$desc.append(' (');$desc.append($qty);$desc.append(')');$row.append($desc);$table.append($row);}}
function incrementCartTotal(){var total=parseInt($('.cart-count').html());if(!total){total=0;}
total++;$('.cart-count').html(total);}
function updateCartCookie(prodCode,qty){var cartCookie=getCookie("reece-cart");var cartContents=new Array();var newProductToAdd={productCode:prodCode,quantity:qty,pack:'ONE'};if(cartCookie){cartContents=JSON.parse(cartCookie);var cartLength=cartContents.length;var productFound=false;for(var i=0;i<cartLength;i++){if(cartContents[i].productCode===prodCode){productFound=true;var currentQty=parseInt(cartContents[i].quantity);currentQty+=parseInt(qty);cartContents[i].quantity=currentQty;}}
if(!productFound){cartContents.push(newProductToAdd);}}else{cartContents.push(newProductToAdd);}
var cookieValue=encodeURIComponent(JSON.stringify(cartContents));document.cookie='reece-cart='+cookieValue+'; expires=Fri, 1 Jan 2031 00:00:01 UTC; path=/';}
function sortAttributeColumns(){$("#accordion .accordion-inner").each(function(){if($(".products-tab",$(this)).length==0){return true;}
var totalHeight=0;var attributes=new Array();$(".products-tab",$(this)).each(function(){var height=$(this).outerHeight();if(!height){$(this).parents('.tab-pane').addClass('active');height=$(this).outerHeight();$(this).parents('.tab-pane').removeClass('active');}
totalHeight+=height;var object={};object.el=$(this);object.height=height;attributes.push(object);});$(".products-tab",$(this)).remove();var warrantyTabPdfs=false;if($(".section",$(this)).length>0){warrantyTabPdfs=$(".section",$(this));$(".section",$(this)).remove();}
var $divLeft=$("<div>").addClass("span6");var $divRight=$("<div>").addClass("span6");var heightToBreak=totalHeight/2;var currentHeight=0;for(var i=0;i<attributes.length;i++){if(currentHeight>=heightToBreak){$divRight.append(attributes[i].el);}else{$divLeft.append(attributes[i].el);}
currentHeight+=attributes[i].height;}
if(warrantyTabPdfs){$divRight.append(warrantyTabPdfs);}
var $wrapper=$("<div>").addClass("row-fluid");$wrapper.append($divLeft).append($divRight);$(this).append($wrapper);});}
function resizeBreadCrumbs(){var ulTotalWidth=$("ul.breadcrumb").outerWidth();var outerULWidth=$("ul.breadcrumb").outerWidth();ulTotalWidth=ulTotalWidth-60;var navBreadCrumbItemsCompactWidth=navBreadCrumbItemsInitialTotalWidth;if((outerULWidth<previousULWidth)||(outerULWidth==previousULWidth)){if(navBreadCrumbItemsCompactWidth>ulTotalWidth){if(ulTotalWidth>650){$('ul.breadcrumb li').each(function(i){if(i>0){var liWidth=$(this).outerWidth();if(i==1){if($("a",this).is(":visible")){$("a",this).hide();$(".dot",this).show();liWidth=30;}}else{$(this).hide();}
navBreadCrumbItemsCompactWidth=navBreadCrumbItemsCompactWidth-liWidth;navBreadCrumbItemsMinimumWidth=navBreadCrumbItemsCompactWidth;if(navBreadCrumbItemsCompactWidth<ulTotalWidth){return false;}}});}}}else if(outerULWidth>previousULWidth){if($(".dot").is(":visible")){var widthOfVisibleLis=0;$('ul.breadcrumb li:visible').each(function(){widthOfVisibleLis+=$(this).outerWidth();});$($("ul.breadcrumb li").get().reverse()).each(function(i){if(i>0){if($(this).is(":hidden")||$("a",this).is(":hidden")){if($(".dot",this).length>0){$(".dot",this).hide();$("a",this).show();}else{$(this).show();}
var liWidth=$(this).outerWidth();var newVisibleLiWidth=widthOfVisibleLis+liWidth;if(newVisibleLiWidth>=ulTotalWidth){if($(".dot",this).is(":hidden")){$("a",this).hide();$(".dot",this).show();}else{$(this).hide();}
return false;}
widthOfVisibleLis=newVisibleLiWidth;}}});}}
previousULWidth=outerULWidth;}
function setPostCodeResult(userpostcode,data){var state=data.branches[0].costStateCode.replace(/^0+/,"");var branchCode=data.branches[0].branchCode.replace(/^0+/,"");var array={state:state,postCode:userpostcode,branchCode:branchCode};document.cookie='reece-user-location='+encodeURI(JSON.stringify(array))+'; expires=Fri, 1 Jan 2021 00:00:01 UTC; path=/';window.location.replace(window.location);}
window.setPostCodeManually=setPostCodeResult;function isNumeric(n){return!isNaN(parseFloat(n))&&isFinite(n);}
function hidenthElementsOnwards(ele,tag,cutoffHeight){$(tag,ele).each(function(j){if($(this).position().top>cutoffHeight){$(this).hide();}});}
function getCookie(cookiename){var name=cookiename+"=";var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var trimmed=cookies[i].trim();if(trimmed.indexOf(name)==0){var encodedValue=trimmed.substring(name.length,trimmed.length);return decodeURIComponent(encodedValue);}}
return"";}
function deleteCookie(name){document.cookie=name+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/';}
function isProductInList(product,list){for(var i=0;i<list.length;i++){if(list[i]==product){return true;}}
return false;}
function removeProductFromList(product,list){for(var i=0;i<list.length;i++){if(list[i]==product){list.splice(i,1);}}
return list;}
if(typeof String.prototype.trim!=='function'){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'');}}})(jQuery);;

/****** FILE: themes/reece/javascript/reece-works-for-you.js *****/
;(function($){$(document).ready(function(){$(".toggle-works-for-you").on('click',function(){$parent=$(this).parents(".row-fluid");$("i.icon-chevron-up").removeClass("icon-chevron-up").addClass("icon-chevron-down");if($($parent).css("max-height")=="70px"){$(".works-section").css("max-height","70px");$("i",$parent).removeClass("icon-chevron-down").addClass("icon-chevron-up");$parent.css("max-height","2000px");}else{$parent.css("max-height","70px");}});});})(jQuery);;

